# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d02f9b6624af31e1dbca64855555c8bc8f6ea03cc9d12ed2ac86618c2780064b786f6a26625a21f48e0144b54611997493ec7eb9c88456976e4be5e4a701297

test:
  secret_key_base: 1db66f263acd950183ca8541255789ff29e55f6a12769b35b3cbe9ae6b7374d7246a1ca23a1b218f6061e61e2d1f797fa8a234fbffe2dd9d4967772f96d21cb8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
